config/routes.rb
Rails.application.routes.draw do

  get    'signup', to: 'users#new'
  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users
  resources :urls, except: [:edit, :update]

  get '/:slug' => 'urls#redirect'

  root 'welcome#index'

end

app/models/url.rb
class Url < ActiveRecord::Base
  belongs_to :user

  before_validation :set_uid
  validates :uid, presence: true
  validates :origin, presence: true
  validates :user, presence: true

  validates_uniqueness_of :origin, scope: :user_id

  private
  def set_uid
    require 'SecureRandom'
    self.uid = SecureRandom.urlsafe_base64(5)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :urls

  validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }



  def self.by_email(email)
    find_by(email: email.downcase)
  end

  def self.authenticate(email, password)
    by_email(email).try(:authenticate, password)
  end

  private
  def sanitize_email
    self.email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user = User.find( session[:user_id] ) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.authenticate(params[:user][:email], params[:user][:password])
    if @user
      session[:user_id] = @user.id
      redirect_to @user
    else
      @user = User.new
      render 'new'
    end
  end

  def destroy
    session.clear
    redirect_to '/'
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  def show
    @url = Url.find_by(uid: params[:id])
  end

  def create
    url = Url.new(origin: url_params[:origin], user: current_user)

    respond_to do |format|
      if url.save
        format.html { redirect_to url_path(url.uid) }
        # format.js   {}
        # format.json { render json: url }
      elsif url.errors[:origin].any?
        existing_url = Url.find_by(origin: url_params[:origin])
        redirect_to url_path(existing_url.uid)
      else
        redirect_to current_user
      end
    end
  end

  def redirect
    url = Url.find_by(uid: params[:slug])
    redirect_to url.origin
  end

  private

  def get_url
    Url.find_by(uid: params[:slug])
  end

  def url_params
    params.require(:url).permit(:origin)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @url = Url.new
    @urls = Url.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @url = Url.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shorty</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>

  <div id="logo">unpretentio.us</div>

  <div class="login">
    <% if current_user %> 
      <%= link_to "Log Out", logout_path, method: :delete%> 
      <%= link_to "Account", user_path(current_user) %>
    <% else %>
      <%= link_to "Login", login_path %> 
      <%= link_to "Sign Up", signup_path %>
    <% end %>
  </div>
</header>

<%= yield %>

</body>
</html>
 

app/views/urls/_form.html.erb
<div class="container">
	<%= form_for(@url, remote: true) do |f| %>
	  <%= f.text_field :origin, placeholder: "Place pretentious link here" %>
	  <%= f.submit value: "Unpretentiousfy!" %>
	<% end %>
</div>

app/views/urls/create.js.erb
$(function() {
	
	// $("#new_article").on("ajax:success", (e, data, status, xhr) ->
 //    $("#new_article").append xhr.responseText
 //  ).on "ajax:error", (e, xhr, status, error) ->
 //    $("#new_article").append "<p>ERROR</p>"

 // #REVIEW JQUERY .ON
 	$("#new_url").on("ajax:success", function(e, data, status, xhr){

 		$('.container').first().append("hello");
 	});


});

app/views/urls/show.html.erb
<div class="container">
  <h3>Congratulations, your shiny new link is:</h3>
  <h1>
    <%= link_to "unpretentio.us/#{@url.uid}", "/#{@url.uid}" %>
  </h1>
</div>

app/views/urls/show.js.erb
$(function() {
	
	// $("#new_article").on("ajax:success", (e, data, status, xhr) ->
 //    $("#new_article").append xhr.responseText
 //  ).on "ajax:error", (e, xhr, status, error) ->
 //    $("#new_article").append "<p>ERROR</p>"

 // #REVIEW JQUERY .ON
 	$("#new_url").on("ajax:success", function(e, data, status, xhr){
 		$('.container').first().append(xhr.responseText);
 	});


});

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.email_field :email, placeholder: "email" %>
  <%= f.password_field :password, placeholder: "password" %>
  <%= f.submit value: 'Sign Up'%>
<% end %>

app/views/users/show.html.erb
<%= render '/urls/form' %>

<div class="container">
  <ul>
    <% @urls.each do |url| %>
      <li>
        <%= link_to "unpretentio.us/#{url.uid}", "/#{url.uid}" %>
      </li>
    <% end %>
  </ul>
</div>

app/views/welcome/index.html.erb
<h1>Unpretentio.us Links</h1>
<h2>A refuge from ridiculously long links.</h2>

<% if current_user%>
  <%= render '/urls/form' %>
<% else%>
  <%= link_to "Become a Member", signup_path  %>
<% end %>